my_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.Home.as_view(), name='home'),
  path('about/', views.about, name='about'),
  path('shoes/', views.shoe_index, name='shoe_index'),
  path('shoes/<int:shoe_id>',views.shoe_detail, name='shoe_detail'),
  path('shoes/create', views.ShoeCreate.as_view(), name='shoe_create'),
  path('shoes/<int:pk>/update', views.ShoeUpdate.as_view(), name='shoe_update'),
  path('shoes/<int:pk>/delete', views.ShoeDelete.as_view(), name='shoe_delete'),
  path('laces/create', views.LaceCreate.as_view(), name='lace_create'),
  path('laces/<int:pk>', views.LaceDetail.as_view(), name='lace_detail'),
  path('laces/', views.LaceList.as_view(), name='lace_index'),
  path('laces/<int:pk>/update/', views.LaceUpdate.as_view(), name='lace_update'),
  path('laces/<int:pk>/delete/', views.LaceDelete.as_view(), name='lace_delete'),
  path('laces/<int:pk>/delete/', views.LaceDelete.as_view(), name='lace_delete'),
  path('shoes/<int:shoe_id>/add-cleaning', views.add_cleaning, name='add_cleaning'),
  path('shoes/<int:shoe_id>/associate-lace/<int:lace_id>/', views.associate_lace, name='associate_lace'),
  path('shoes/<int:shoe_id>/disassociate-lace/<int:lace_id>/', views.disassociate_lace, name='disassociate_lace'),
  path('accounts/signup/', views.signup, name='signup'),
] 

shoedex/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

my_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


# Create your models here.
class Lace(models.Model):
  color = models.CharField(max_length=20)
  
  def __str__(self):
    return self.color
  
  def get_absolute_url(self):
    return reverse('lace_detail', kwargs={'pk': self.id})
  
class Shoe(models.Model):
  model = models.CharField(max_length=50)
  brand = models.CharField(max_length=20)
  purchase_date = models.DateField()
  size = models.DecimalField(max_digits=4, decimal_places=1)
  price = models.DecimalField(max_digits = 10, decimal_places = 2)
  description = models.TextField(max_length=250)
  current_condition=models.CharField(
    choices=[('1', 'Deadstock'), ('2', 'VNDS'), ('3', 'NDS'), ('4', 'Used'), ('5', 'Very Used')]
  )
  photo = models.ImageField(upload_to='shoes/', blank = True)
  laces = models.ManyToManyField(Lace)
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  
  def __str__(self):
    return self.model
  
  def get_absolute_url(self):
    return reverse("shoe_detail", kwargs={"shoe_id": self.id})

class Cleaning(models.Model):
  date = models.DateField()
  confirmation = models.BooleanField('Washed')
  shoe = models.ForeignKey(Shoe, on_delete=models.CASCADE)
  
  def __str__ (self):
    status = 'Washed' if self.confirmation else 'Not washed'
    return f'{status} {self.shoe.model} on {self.date}'

my_app/forms.py
from django import forms
from .models import Cleaning

class CleaningForm(forms.ModelForm):
    class Meta:
        model = Cleaning
        fields = ['date', 'confirmation']
        widgets = {
            'date': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'placeholder': 'Select a date',
                    'type': 'date'
                }
            ),
        }

my_app/views.py
from django.shortcuts import render, redirect
from .models import Shoe, Lace
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView, ListView
from django.contrib.auth.views import LoginView
from .forms import CleaningForm
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

def about(request):
  return render(request, 'about.html')

@login_required
def shoe_index(request):
  shoes = Shoe.objects.filter(user=request.user)
  return render(request, 'shoes/index.html', {'shoes': shoes})

@login_required
def shoe_detail(request, shoe_id):
  shoe=Shoe.objects.get(id=shoe_id)
  laces_shoe_doesnt_have = Lace.objects.exclude(id__in = shoe.laces.all().values_list('id'))
  cleaning_form = CleaningForm()
  return render(request, 'shoes/detail.html', {'shoe': shoe, 'laces': laces_shoe_doesnt_have, 'cleaning_form': cleaning_form})

@login_required
def add_cleaning(request, shoe_id):
  form = CleaningForm(request.POST)
  if form.is_valid():
    new_cleaning = form.save(commit=False)
    new_cleaning.shoe_id = shoe_id
    new_cleaning.save()
  return redirect('shoe_detail', shoe_id = shoe_id)

@login_required
def associate_lace(request, shoe_id, lace_id):
  Shoe.objects.get(id=shoe_id).laces.add(lace_id)
  return redirect('shoe_detail', shoe_id = shoe_id)

@login_required
def disassociate_lace(request, shoe_id, lace_id):
  Shoe.objects.get(id=shoe_id).laces.remove(lace_id)
  return redirect('shoe_detail', shoe_id = shoe_id)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('shoe_index')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'signup.html', context)

class Home(LoginView, LoginRequiredMixin):
  template_name = 'home.html'

class ShoeCreate(CreateView, LoginRequiredMixin):
  model = Shoe
  fields = ['model', 'brand', 'purchase_date', 'size', 'price', 'description', 'current_condition', 'photo' ]
  # success_url = '/shoes/'
  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)
  
class ShoeUpdate(UpdateView, LoginRequiredMixin):
  model = Shoe
  fields = ['model', 'brand', 'purchase_date', 'size', 'price', 'description', 'current_condition', 'photo' ]
  
class ShoeDelete(DeleteView, LoginRequiredMixin):
  model = Shoe
  success_url = '/shoes/'

class LaceCreate(CreateView, LoginRequiredMixin):
  model = Lace
  fields = '__all__'
  
class LaceDetail(DetailView, LoginRequiredMixin):
  model = Lace
  
class LaceList (ListView, LoginRequiredMixin):
  model = Lace
  
class LaceUpdate (UpdateView, LoginRequiredMixin):
  model = Lace
  fields = 'color'

class LaceDelete (DeleteView, LoginRequiredMixin):
  model = Lace
  success_url = '/laces/'
  

my_app/templates/about.html
{% extends "base.html" %}
{% block content %}
  <h1>Welcome to ShoeDex!</h1>
  <p class='page-content'>ShoeDex is where you will share the shoes within your collection. You can add details of when you received the shoes, </p>
{% endblock %}

my_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <title>ShoeDex</title>
    {% block head %}

    {% endblock %}
  </head>
  <body>
    <header>
      <div class='header-logo-container'>
        <img src="{%static 'images/shoedex-logo-name.png'%}" alt="shoedex-logo-name">
      </div>
      <nav>
        <ul>
          {% if user.is_authenticated %}
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'shoe_create' %}">Add a Shoe</a></li>
            <li><a href="{% url 'shoe_index' %}">All Shoes</a></li>
            <li><a href="{% url 'lace_create' %}">Add a Lace</a></li>
            <li><a href="{% url 'lace_index' %}">All Laces</a></li>
            <li>
              <form id="logout-form" method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit">Log out</button>
              </form>
            </li>
          {% else %}
            <li><a href="{% url 'home' %}">Login</a></li>
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main>
      {% block content %}

      {% endblock %}
    </main>
  </body>
</html>

my_app/templates/home.html
{% extends "base.html" %}
{% block content %}
{% if not user.is_authenticated %}
  <section>
    <form action="{% url 'home' %}" method="post" class="login">
      <h1>Login</h1>
      {% csrf_token %} {{ form.as_p }}
      <input type="hidden" name="next" value="{{ next }}" />
      <button type="submit" class="btn submit">Login</button>
    </form>
  </section>
{% endif %}
{% endblock  %}

my_app/templates/my_app/lace_confirm_delete.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Delete Lace?</h1>
</div>
<h2>Are you sure you want to delete {{ lace.color }} laces?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'lace_detail' lace.id %}" class="btn secondary"> Cancel </a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

my_app/templates/my_app/lace_detail.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/laces/lace-detail.css' %}" />
{% endblock %} 
{% block content %}

<div class="card" style="border-color: {{ lace.color }}">
  <div class="card-bg" style="background-color: {{ lace.color }}"></div>
  <div class="card-content">
    <h2>A {{ lace.color }} lace</h2>
  </div>
</div>
<a href="{% url 'lace_update' lace.id %}" class="btn warn">Edit</a>
<a href="{% url 'lace_delete' lace.id %}" class="btn danger">Delete</a>


{% endblock %}

my_app/templates/my_app/lace_form.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
  <link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}
  <div class="page-header">
    {% if object %}
      <h1>Edit {{object.name}}</h1>
    {% else %}
      <h1>Add a Lace</h1>
    {% endif %}
  </div>
  <form action="" method="post" class="form-container" autocomplete="off">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit" class="btn submit">Submit!</button>
  </form>

{% endblock %}

my_app/templates/my_app/lace_list.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/laces/lace-index.css' %}" />
{% endblock %} 
{% block content %}

<section class="page-header">
  <h1>All Shoe Lace Colors</h1>
</section>

<section class="card-container">
  {% for lace in lace_list %}
    <div class="card" style="border-color: {{ lace.color }}">
      <div class="card-bg" style="background-color: {{ lace.color }}"></div>
      <a href="{% url 'lace_detail' lace.id %}">
        <div class="card-content">
          <h2>Lace Color: {{ lace.color }}</h2>

        </div>
      </a>
    </div>
  {% endfor %}
</section>

{% endblock %}

my_app/templates/my_app/shoe_confirm_delete.html
{% extends 'base.html' %}  
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Delete Shoe?</h1>
</div>

<h2>Are you sure you want to delete {{ shoe.name }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'shoe_detail' shoe.id %}" class="btn secondary">Cancel</a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

my_app/templates/my_app/shoe_form.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}

<div class="page-header">
  {% if cat %}
    <h1>Edit {{ shoe.name }}</h1>
  {% else %}
    <h1>Add a Shoe</h1>
  {% endif %}
</div>

<form action="" method="post" class="form-container" enctype="multipart/form-data">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

my_app/templates/shoes/detail.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" href="{% static 'css/shoes/shoe-detail.css' %}" />
{% endblock %}
{% block content %}
  <section class="shoe-container">
    <div class="shoe-img">
      <div class="shoe-details">
        <h1>{{ shoe.model }}</h1>
        <h2>Brand: {{ shoe.brand }}</h2>
        <h2>Purchased: {{ shoe.purchase_date }}</h2>
        <h2>Size: {{ shoe.size }}</h2>
        <h2>Bought Price: {{ shoe.price }}</h2>
        <p>Details: {{ shoe.description }}</p>

        <div class="shoe-actions">
          <a href="{% url 'shoe_update' shoe.id %}" class="btn warn">Edit</a>
          <a href="{% url 'shoe_delete' shoe.id %}" class="btn danger">Delete</a>
        </div>
      </div>
    </div>
  </section>
    <div class="cleaning-shoe-container">
      <section class="cleanings">
        <div class="subsection-title">
          <h2>Cleaning</h2>
        </div>

        <h3>Add Cleaning</h3>
        <!-- Add just ab%ove the feedings table -->
        <form action="{% url 'add_cleaning' shoe.id%}" method="post" class="subsection-content" autocomplete="off">
          {% csrf_token %}
          {{ cleaning_form.as_p }}
          <button type="submit" class="btn submit">Add Cleaing</button>
        </form>

        <table>
          <thead>
            <tr>
              <th>Date</th>
              <th>Washed</th>
            </tr>
          </thead>
          <tbody>
            {% for cleaning in shoe.cleaning_set.all %}
              <tr>
                <td>{{ cleaning.date }}</td>
                <td>
                  {% if cleaning.confirmation %}
                    Yes
                  {% else %}
                    No
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </section>
    </div>

    <section class="lace">
      <div class="subsection-title">
        <h2>Laces</h2>
      </div>
    <h3>{{ shoe.model }}'s Laces</h3>
    <div class="subsection-content">
      {% if shoe.laces.count %}
        {% for lace in shoe.laces.all %}
          <div class="lace-container">
            <div class="color-block" style="background-color: {{ lace.color }}"></div>
            <a href="{% url 'lace_detail' lace.id %}"><p>{{ lace.color }} Laces</p></a>
            <form action="{% url 'disassociate_lace' shoe.id lace.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger">Remove Laces</button>
            </form>
          </div>
        {% endfor %}
      {% else %}
        <p class="no-laces">{{ shoe.model }} doesn't have any laces!</p>
      {% endif %}
    </div>

    <h3>Available Laces</h3>
    <div class="subsection-content">
      {% if laces.count %}
        {% for lace in laces.all %}
          <div class="lace-container">
            <div class="color-block" style="background-color: {{ lace.color }}"></div>
            <a href="{% url 'lace_detail' lace.id %}"><p>{{ lace.color }} Laces</p></a>
            <form action="{% url 'associate_lace' shoe.id lace.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn submit">Add Laces</button>
            </form>
          </div>
        {% endfor %}
      {% else %}
        <p class="all-toys">{{ shoe.model }} already has all the available laces 🥳</p>
      {% endif %}
    </div>
  </section>
{% endblock %}

my_app/templates/shoes/index.html
{% extends "base.html" %}
{% load static %}
{% block head %}
  <link rel="stylesheet" href="../static/css/shoes/shoe-index.css">
{% endblock %}

{% block content %}
  <section class="card-container">
    {% for shoe in shoes %}
      <div class="card">
        <a href="{% url 'shoe_detail' shoe.id %}">
          <div class="card-content">
            {% if shoe.photo %}
              <img
                src= '{{shoe.photo.url}}'
                alt='{{shoe.model}}'
              />
            {% else %}
              <p>You do not have any photos for this shoe!</p>
            {%endif%}
            <h2 class="card-title">{{ shoe.model }}</h2>
            <p>
              <small>{{ shoe.description }}</small>
            </p>
          </div>
        </a>
      </div>
    {% endfor %}
  </section>
{% endblock %}

my_app/templates/signup.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}
<div class="page-header">
  <h1>Sign Up</h1>
  <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer" />
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}